// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ReadData():Promise<Array<main.WatchList>>;

export function WriteData(arg1:Array<main.WatchList>):Promise<void>;
