// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMovieToList(arg1:main.Movie,arg2:string):Promise<void>;

export function AddTVShowToList(arg1:main.TVShow,arg2:string):Promise<void>;

export function GetCustomMoviesLists():Promise<Array<main.MovieList>>;

export function GetCustomTVShowsLists():Promise<Array<main.TVShowList>>;

export function GetMovieWatchStatus(arg1:number):Promise<string>;

export function GetMoviesStatusLists():Promise<Array<main.MovieList>>;

export function GetTVShowWatchStatus(arg1:number):Promise<string>;

export function GetTVShowsStatusLists():Promise<Array<main.TVShowList>>;

export function UpdateMovieWatchStatus(arg1:main.Movie,arg2:string):Promise<void>;

export function UpdateTVShowEpisodeWatchStatus(arg1:main.TVShow,arg2:number,arg3:number):Promise<void>;

export function UpdateTVShowWatchStatus(arg1:main.TVShow,arg2:string):Promise<void>;
