// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMovieToList(arg1, arg2) {
  return window['go']['main']['UserData']['AddMovieToList'](arg1, arg2);
}

export function AddTVShowToList(arg1, arg2) {
  return window['go']['main']['UserData']['AddTVShowToList'](arg1, arg2);
}

export function GetCustomMoviesLists() {
  return window['go']['main']['UserData']['GetCustomMoviesLists']();
}

export function GetCustomTVShowsLists() {
  return window['go']['main']['UserData']['GetCustomTVShowsLists']();
}

export function GetMovieWatchStatus(arg1) {
  return window['go']['main']['UserData']['GetMovieWatchStatus'](arg1);
}

export function GetMoviesStatusLists() {
  return window['go']['main']['UserData']['GetMoviesStatusLists']();
}

export function GetTVShowWatchStatus(arg1) {
  return window['go']['main']['UserData']['GetTVShowWatchStatus'](arg1);
}

export function GetTVShowsStatusLists() {
  return window['go']['main']['UserData']['GetTVShowsStatusLists']();
}

export function UpdateMovieWatchStatus(arg1, arg2) {
  return window['go']['main']['UserData']['UpdateMovieWatchStatus'](arg1, arg2);
}

export function UpdateTVShowEpisodeWatchStatus(arg1, arg2, arg3) {
  return window['go']['main']['UserData']['UpdateTVShowEpisodeWatchStatus'](arg1, arg2, arg3);
}

export function UpdateTVShowWatchStatus(arg1, arg2) {
  return window['go']['main']['UserData']['UpdateTVShowWatchStatus'](arg1, arg2);
}
