// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMovieToList(arg1, arg2) {
  return window['go']['main']['UserData']['AddMovieToList'](arg1, arg2);
}

export function AddTVShowToList(arg1, arg2) {
  return window['go']['main']['UserData']['AddTVShowToList'](arg1, arg2);
}
