// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMovieToList(arg1:string,arg2:main.Movie):Promise<void>;

export function AddTVShowToList(arg1:string,arg2:main.TVShow):Promise<void>;
