// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMovieToList(arg1:string,arg2:main.Movie):Promise<boolean>;

export function AddTVShowToList(arg1:string,arg2:main.TVShow):Promise<boolean>;

export function MoveMovieToList(arg1:string,arg2:string,arg3:main.Movie):Promise<boolean>;

export function MoveTVShowToList(arg1:string,arg2:string,arg3:main.TVShow):Promise<boolean>;

export function RemoveMovieFromList(arg1:string,arg2:main.Movie):Promise<boolean>;

export function RemoveTVShowFromList(arg1:string,arg2:main.TVShow):Promise<boolean>;
